stages:
- name: Test PackageGenerator
- name: Run Tests
- name: Build & Post on GitHub
  if: branch = master
jobs:
  include:
  - stage: Test PackageGenerator
    language: php
    php: '7.3'
    os: linux
    before_script:
    - cd package
    - composer install
    script:
    - vendor/bin/phpunit --configuration ../tests/phpunit/phpunit.xml
  - stage: Test PackageGenerator
    language: node_js
    node_js: '8.15.0'
    before_script:
    - cd tests/jasmine
    - yarn install
    - yarn global add grunt-cli
    script:
    - grunt test-js
  - stage: Run Tests
    language: php
    php: '7.3'
    services:
    - docker
    env:
    - SUGAR_VERSION=10.2 SUGAR_EDITION=Ent
    before_script:
    - cd package
    - composer install
    - "./pack.php -v $(date +'%Y%m%d-%H.%M.%S')"
    - cd ../scripts
    - sudo service mysql stop
    script:
    - "./SetupEnvAndRunTests.sh $SUGARCLUB_USERNAME $SUGARCLUB_PASSWORD $SUGAR_VERSION
      $SUGAR_EDITION $GITHUB_USERNAME $GITHUB_PASSWORD workspace/sugardocker"
  - stage: Run Tests
    language: php
    php: '7.3'
    services:
    - docker
    env:
    - SUGAR_VERSION=10.2 SUGAR_EDITION=Pro
    before_script:
    - cd package
    - composer install
    - "./pack.php -v $(date +'%Y%m%d-%H.%M.%S')"
    - cd ../scripts
    - sudo service mysql stop
    script:
    - "./SetupEnvAndRunTests.sh $SUGARCLUB_USERNAME $SUGARCLUB_PASSWORD $SUGAR_VERSION
      $SUGAR_EDITION $GITHUB_USERNAME $GITHUB_PASSWORD workspace/sugardocker"
  - stage: Build & Post on GitHub
    language: php
    php: '7.3'
    before_script:
    - cd package
    - composer install
    script:
    - "./pack.php -v $(date +'%Y%m%d-%H.%M.%S')"
    - "./pack.php -v $(date +'%Y%m%d-%H.%M.%S') -w 40"
    - "./pack.php -v $(date +'%Y%m%d-%H.%M.%S') -p"
    before_deploy: git tag "$(date +'%Y%m%d-%H.%M.%S')-$(git log --format=%h -1)"
    deploy:
      provider: releases
      api_key: "b84a1cc0057c477f3be6142155194a88d02c20dc"
      file_glob: true
      file: releases/sugarcrm-ProfessorM-*.zip
